# Generated by Django 2.1.8 on 2019-11-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_superuser',
            new_name='is_admin',
        ),
    ]
