# Generated by Django 2.1.8 on 2019-11-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0003_auto_20191109_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(default=3)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_added', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('rel_date', models.DateTimeField(blank=True)),
                ('nicotine', models.FloatField(blank=True)),
                ('TAR', models.FloatField(blank=True)),
                ('is_menthol', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('rel_date', models.DateTimeField(blank=True)),
                ('nicotine', models.FloatField()),
                ('TAR', models.FloatField()),
                ('is_menthol', models.BooleanField()),
                ('score', models.FloatField()),
                ('total_like', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-rel_date'],
            },
        ),
        migrations.CreateModel(
            name='Cigarettes',
            fields=[
                ('tobacco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cigarettes.Tobacco')),
                ('is_local', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cigarettes.tobacco',),
        ),
        migrations.CreateModel(
            name='ElecCigarettes',
            fields=[
                ('tobacco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cigarettes.Tobacco')),
                ('c_type', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cigarettes.tobacco',),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='like_user',
            field=models.ManyToManyField(null=True, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cigarettes.tobacco_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belongs_to_tobacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cigarettes.Tobacco'),
        ),
        migrations.AddField(
            model_name='comment',
            name='belongs_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
