# Generated by Django 2.1.8 on 2019-11-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_elec',
            field=models.BooleanField(default=False),
        ),
    ]
