# Generated by Django 2.1.8 on 2019-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0002_request_is_elec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='feel_of_hit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
