# Generated by Django 2.1.8 on 2019-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0005_auto_20191110_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigarettes',
            name='is_menthol',
            field=models.BooleanField(default=False),
        ),
    ]
