# Generated by Django 2.1.8 on 2019-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0006_auto_20191110_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_menthol',
        ),
        migrations.AlterField(
            model_name='cigarettes',
            name='is_menthol',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_elec',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='feel_of_hit',
            field=models.CharField(max_length=10),
        ),
    ]
