# Generated by Django 2.1.8 on 2019-11-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0007_auto_20191110_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feel_of_hit',
            field=models.CharField(default='중', max_length=10),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='feel_of_hit',
            field=models.CharField(default='중', max_length=10),
        ),
    ]
