# Generated by Django 2.1.8 on 2019-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0008_auto_20191110_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feel_of_hit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='feel_of_hit',
            field=models.CharField(default='데이터 없음', max_length=10),
        ),
    ]
