# Generated by Django 2.1.8 on 2019-11-10 04:10

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0009_auto_20191110_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobacco',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='media/cigarette'),
        ),
    ]
