# Generated by Django 2.1.8 on 2019-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigarettes', '0010_auto_20191110_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
